import type { NextPage } from 'next'
import Head from 'next/head'

import Nominee from "@components/awards/Nominee";
import ResultModal from "@components/awards/ResultModal";
import styles from "@styles/Awards.module.css"

const Awards: NextPage = () => {
    return (
    <div>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
            <div className="row">
                <h1 className="text-center">AWARDS 2021</h1>
            </div>

            <div className="row">
                <div className="col">
                <h3 className={ styles.category }>
                    Category 1
                </h3>
                </div>
            </div>

            <div className="row">
                <div className="col-md-4">
                    <Nominee />
                </div>

                <div className="col-md-4">
                    <Nominee />
                </div>

                <div className="col-md-4">
                    <Nominee />
                </div>
            </div>

            <div className="row">
                <div className="col-md-4">
                    <Nominee />
                </div>

                <div className="col-md-4">
                    <Nominee />
                </div>

                <div className="col-md-4">
                    <Nominee />
                </div>
            </div>
        </div>
      </main>
    </div>
    )
}

export default Awards;