import type { NextPage } from 'next'
import Head from 'next/head'
import styles from "@styles/Awards.module.css"

const Awards: NextPage = () => {
    return (
    <div>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Good Luck!
        </h1>
      </main>
    </div>
    )
}

export default Awards;